# Generated by Django 4.2.7 on 2024-01-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='card_exp_date',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='card_number',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='wallet_address',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
